config/routes.rb
Rails.application.routes.draw do

  resources :users
  resources :moods
  resources :mood_types do
    collection do
      get :reset , action: :reset, as: 'reset'
    end
  end

end

app/models/mood.rb
class Mood < ActiveRecord::Base
  belongs_to :user
  belongs_to :mood_type
end

app/models/mood_type.rb
class MoodType < ActiveRecord::Base
  has_many :moods
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :moods
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/mood_types_controller.rb
class MoodTypesController < ApplicationController

  def index
    @mood_types = MoodType.all

    respond_to do |format|
      format.html
      format.json { render :json => @mood_types.to_json }
    end
  end

  def reset
    @mood_types = MoodType.all
    @mood_types.each do |mood_type|
      mood_type.destroy
    end

    MoodType.create(id: 1, name: "Happy")
    MoodType.create(id: 2, name: "Sad")
    MoodType.create(id: 3, name: "Mad")
    MoodType.create(id: 4, name: "Normal")
    MoodType.create(id: 5, name: "Lucky")
    MoodType.create(id: 6, name: "Warm")

    redirect_to :action => :index
  end

end

app/controllers/moods_controller.rb
class MoodsController < ApplicationController

  def index
    @moods = Mood.all

    respond_to do |format|
      format.html
      format.json { render :json => @moods.to_json }
    end
  end

  def new
    @mood = Mood.new
    # @mood_collection = MoodType.all
  end

  def create
    @mood = Mood.new(mood_params)
    @mood.save

    respond_to do |format|
      format.html { redirect_to :action => :index }
      format.json { render status: 500 }
    end
  end

  def destroy
    @mood = Mood.find(params[:id])
    @mood.destroy

    respond_to do |format|
      format.html { redirect_to :action => :index }
      format.json { render status: 500 }
    end
  end

private
  def mood_params
    params.require(:mood).permit(:user_id, :mood_type_id, :sentance, :locationX, :locationY)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @users = User.all

    respond_to do |format|
      format.html
      format.json { render :json => @users.to_json }
    end
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    @user.save

    respond_to do |format|
      format.html { redirect_to :action => :index }
      format.json { render status: 500 }
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to :action => :index }
      format.json { render status: 500 }
    end
  end

private
  def user_params
    params.require(:user).permit(:name)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/mood_types_helper.rb
module MoodTypesHelper
end

app/helpers/moods_helper.rb
module MoodsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>DatabaseServer</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/mood_types/index.html.erb
<div class="container">
  <div class="col-xs-12">
    <h3>Users List</h3>


    <table class="table table-condensed table-hover">
      <thead>
        <tr>
          <th>ID</th>
          <th>Mood Type</th>
        </tr>
      </thead>
      <tbody>
        <% @mood_types.each do |mood_type| %>
          <tr>
            <td><%= mood_type.id %></td>
            <td><%= mood_type.name %></td>
          </tr>
        <% end %>
      </tbody>
    </table>

  </div>
</div>

app/views/moods/index.html.erb
<div class="container">
  <div class="col-xs-12">
    <h3>Users List</h3>


    <table class="table table-condensed table-hover">
      <thead>
        <tr>
          <th>ID</th>
          <th>User name</th>
          <th>Mood</th>
          <th>Sentance</th>
          <th>Location</th>
          <th></th>
        </tr>
      </thead>
      <tbody>
        <% @moods.each do |mood| %>
          <tr>
            <td><%= mood.id %></td>
            <td><%= mood.user.nil? ? mood.user_id : mood.user.name %></td>
            <td><%= mood.mood_type.name %></td>
            <td><%= mood.sentence %></td>
            <td><%= "(#{mood.locationX}, #{mood.locationY})" %></td>
            <td><%= link_to "delete", mood_path(mood), method: "delete", data: { confirm: "Are you sure?" } %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
    <%= link_to 'New Mood', :controller => 'moods', :action => 'new' %>

  </div>
</div>

app/views/moods/new.html.erb
<%= simple_form_for @mood, url: moods_path,
    html: {method: :post, class: 'form-vertical' } do |f| %>

  <%= f.input :user_id %>
  <%= f.input :mood_type_id, as: :select, collection: MoodType.all, include_blank: false %>
  <%= f.input :sentence %>
  <%= f.input :locationX %>
  <%= f.input :locationY %>

  <%= f.submit "Create", class: "btn btn-primary" %>

<% end %>

app/views/users/index.html.erb
<div class="container">
  <div class="col-xs-12">
    <h3>Users List</h3>


    <table class="table table-condensed table-hover">
      <thead>
        <tr>
          <th>ID</th>
          <th>Username</th>
          <th></th>
        </tr>
      </thead>
      <tbody>
        <% @users.each do |user| %>
          <tr>
            <td><%= user.id %></td>
            <td><%= link_to(user.name, user_path(user), :target => '_blank') %></td>
            <td><%= link_to "delete", user_path(user), method: "delete", data: { confirm: "Are you sure?" } %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
    <%= link_to 'New User', :controller => 'users', :action => 'new' %>

  </div>
</div>

app/views/users/new.html.erb
<%= simple_form_for @user, url: users_path,
    html: {method: :post, class: 'form-vertical' } do |f| %>

  <%= f.input :name %>
  <%= f.submit "Create", class: "btn btn-primary" %>

<% end %>